### ISSUE TITLE
IS it paper's code ?

### ISSUE THREAD

**Issue by ricardo-kcc** [WorldExecute/fuzzer#1]
could you introduce this tools' features ?

**Comment by WorldExecute** [comment]
I'm sorry for replying to you so late (as this account is a temporary one and not our regular account). 
> IS it paper's code ?

Yes, this is indeed the code for one of our papers, but it is not yet complete and stable. 
> could you introduce this tools' features ?

And the paper is still unpublished, so it's not convenient to reveal too much information.
In general, the tool is to improve fuzzing efficiency by testing a special PUT that eliminates branch dependencies through the second fuzzing process.
